export const SET_AUTH_EMAIL = "SET_AUTH_EMAIL";
export const SET_AUTH_PASSWORD = "SET_AUTH_PASSWORD";
export const ADD_INITIAL_VALUE = "ADD_INITIAL_VALUE";
export const ADD_ADDRESS_INITIAL_VALUE = "ADD_ADDRESS_INITIAL_VALUE";
export const SAVE_NEW_WORK_EXPERIENCE = "SAVE_NEW_WORK_EXPERIENCE";
export const REMOVE_SAVED_WORK_EXPERIENCE = "REMOVE_SAVED_WORK_EXPERIENCE";
export const WORK_EXPERIENCE_EDIT_MODAL_VISIBLE = "WORK_EXPERIENCE_EDIT_MODAL_VISIBLE";
export const SAVE_EDITED_WORK_EXPERIENCE = "SAVE_EDITED_WORK_EXPERIENCE";