export const ADD_SIZE_CIRCLE = "ADD_SIZE_CIRCLE";
export const DISPLAY_NONE_CIRCLE = "DISPLAY_NONE_CIRCLE";
export const SHOW_RESUME = "SHOW_RESUME";
export const SHOW_TEMPLATE = "SHOW_TEMPLATE";
export const SIGNED_NEXT_WIZARD_STEP = "SIGNED_NEXT_WIZARD_STEP";
export const SIGNED_BACK_WIZARD_STEP = "SIGNED_BACK_WIZARD_STEP";
export const HOME_CIRCLE_VISIBLE = "HOME_CIRCLE_VISIBLE";
export const RESUME_NUMBER = "RESUME_NUMBER";
export const RESUME_COLOR = "RESUME_COLOR";
export const RESUME_COLOR_BOX = "RESUME_COLOR_BOX";


