export const SHOW_ALL_RESUMES = "SHOW_ALL_RESUMES";
export const SHOW_COVER_LETTERS = "SHOW_COVER_LETTERS";
export const SHOW_DOCUMENTS = "SHOW_DOCUMENTS";
export const SHOW_DONE_RESUMES = "SHOW_DONE_RESUMES";
